version: "3.5"

volumes:
  grafanadata: {}

networks:
  default:
    external:
      name: tianxun


services:

  prometheus-anomaly-dector:
    build: .
    ports:
      - 8080:8080
    #image: csighub.tencentyun.com/tianxun/prometheus-anomaly-detector:latest
    image: quay.io/aicoe/prometheus-anomaly-detector:latest
    environment:
      - FLT_PROM_URL=http://victoriametrics:8428
      - FLT_RETRAINING_INTERVAL_MINUTES=120
      - FLT_METRICS_LIST='vm_rows_inserted_total'
      - APP_FILE=app.py
      - FLT_DATA_START_TIME=3d
      - FLT_ROLLING_TRAINING_WINDOW_SIZE=15d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure